language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.3.1
  - DJANGO=1.4
  - DJANGO=1.5
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install coverage>=3.6
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - pip install -q -e . --use-mirrors
before_script:
  - "pep8 --exclude=migrations --ignore=W291 moderation tests"
  - pyflakes -x W src
script:
  - coverage run setup.py test
after_success:
  - coverage report
  - pip install --quiet --use-mirrors python-coveralls
  - coveralls