language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
install:
  - pip install zc.buildout
  - pip install pil
  - pip install pep8
  - python bootstrap.py
  - bin/buildout
  - bin/django-1.2 syncdb --noinput
   
# command to run tests
script: bin/test.sh
