language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.4"
env:
  - DJANGO=1.3.7
  - DJANGO=1.4.8
  - DJANGO=1.5.4
  - DJANGO=1.6.5
install:
  - pip install -q Django==$DJANGO
  - pip install -q coverage>=3.6
  - pip install -q flake8
  - pip install -q -e .
before_script:
  - flake8 --exclude=migrations --ignore=W291,F403 moderation tests
script:
  - coverage run setup.py test
after_success:
  - coverage report
  - pip install --quiet --use-mirrors python-coveralls
  - coveralls